Repository CUBRID/cubrid-manual, pull requests merged in 2020-11, with the labels that each got.

#196 update broker_access_log (eng/kor)
  en/admin/control.rst
  en/api/python.rst
  ko/admin/control.rst
  ko/api/python.rst
Labels: english, korean, manual

#197 [CUBRIDMAN-19] update jdbc_driver usage (eng/kor)
  en/api/jdbc.rst
  en/api/python.rst
  ko/api/jdbc.rst
  ko/api/python.rst
Labels: english, korean, manual

#195 [CUBRIDMAN-8] Fix the file path for server error code
  en/admin/control.rst
  ko/admin/control.rst
Labels: english, korean

#194 [CUBRIDMAN-17] CYCLE and NOCYCLE options are omitted in CREATE SERIAL and ALTER SERIAL synopses
  en/sql/schema/serial_stmt.rst
  ko/sql/schema/serial_stmt.rst
Labels: english, korean, manual

#199 [CUBRIDMAN-19] update broker_access_log (Eng/Kor)
  en/admin/control.rst
  ko/admin/control.rst
Labels: english, korean, manual

#193 [CUBRIDMAN-15] Build fail with python3
  en/_templates_org/layout.html
  ko/_templates_org/layout.html
Labels: task

#202 [CUBRIDMAN-19] update jdbc_driver usage
  en/api/jdbc.rst
  ko/api/jdbc.rst
Labels: english, korean, manual

#200 [CUBRIDMAN-19] update csql session command
  en/qrytool.rst
  ko/qrytool.rst
Labels: english, korean, manual

#207 [CUBRIDMAN-6] Remove unused naver analytics script
  en/_templates_org/layout.html
  ko/_templates_org/layout.html
Labels: task

#208 [CUBRIDMAN-15] Add Travis test environment for python 3.6
  .travis.yml
Labels: task

#204 [CUBRIDMAN-9] The max length of CHAR-type changed to 256MB (spec. changed)
  en/sql/datatype.rst
Labels: english, manual

#211 [CUBRIDMAN-10] manual for CBRD-23690 (replication script)
  en/ha.rst
Labels: english, manual

#215 [CUBRIDMAN-21] change an limit value of max_client
  en/admin/config.rst
  ko/admin/config.rst
Labels: english, korean

#218 [CUBRIDMAN-22] Enhance compactdb utility
  en/admin/admin_utils.rst
  ko/admin/admin_utils.rst
Labels: english, korean

#216 [CUBRIDMAN-23] remove -u and -p option at tranlist and -p otion only work with -i or --kill option on killtran utility.
  en/admin/admin_utils.rst
  ko/admin/admin_utils.rst
Labels: english, korean

#219 [CUBRIDMAN-10] manual for CBRD-23690 (replication script) (Korean)
  ko/ha.rst
Labels: korean, manual
