Repository CUBRID/cubrid-manual, pull requests merged in 2020-05, with the labels that each got.

#106 [CBRD-23624] Add Travis for manual
  .travis.yml
  en/conf.py
  ko/conf.py
Labels: enhancement

#103 [CBRD-21565] Add system parameter for Java SP server to apply JVM options
  ko/admin/config.rst
Labels: enhancement, korean, manual

#107 [CBRD-21565] Add system parameter for Java SP server to apply JVM options (#101, #103)
  en/admin/config.rst
  ko/admin/config.rst
Labels: english, enhancement, korean, manual

#109 [CBRD-23624] Add Travis for manual (#106)
  .travis.yml
  en/conf.py
  ko/conf.py
Labels: enhancement

#110 [CBRD-23662] [10.2] translate english manual to korean
  ko/sql/function/json_fn.rst
Labels: korean, manual

#112 [CBRD-23662] Translate JSON aggregate functions
  ko/sql/function/analysis_fn.rst
Labels: korean, manual

#115 [CBRD-23662] json-function: translate english manual to korean
  ko/sql/function/index.rst
  ko/sql/function/json_fn.rst
Labels: korean, manual

#114 [CBRD-23662] Translate update compatibility chapter
  ko/install.rst
Labels: korean, manual

#113 [CBRD-23662] Translate JSON system parameter
  ko/admin/config.rst
Labels: korean, manual

#122 [CBRD-23637] add description for secure jdbc driver to the manual
  en/api/jdbc.rst
  ko/api/jdbc.rst
Labels: manual
