Repository CUBRID/cubrid-manual, pull requests merged in 2020-07, with the labels that each got.

#182 [CBRD-23662] translate english manual to korean (from CBRD-23489)
  ko/admin/config.rst
  ko/admin/db_manage.rst
  ko/intro.rst
Labels: korean, manual

#184 [CBRD-23662] translate english manual to korean (from CBRD-23494)
  ko/admin/admin_utils.rst
Labels: korean, manual

#185 [CBRD-23662] translate english manual to korean (from CBRD-23494)
  ko/admin/admin_utils.rst
Labels: korean, manual

#183 [CBRD-23662] translate english manual to korean (from CBRD-23494)
  ko/admin/admin_utils.rst
Labels: korean, manual

#186 [CBRD-23662] Translate English manual of 10.2 to Korean (CBRD-23500 BU Lock PR #82)
  ko/sql/transaction.rst
Labels: korean, manual

#158 [CBRD-23662] translate english manual to korean (PHP Driver)
  ko/api/php.rst
  ko/images/image57.jpg
  ko/images/image58.jpg
Labels: korean, manual

#187 [CBRD-23662] [10.2] translate english manual to korean - modify English manual
  en/admin/admin_utils.rst
  en/env.rst
  en/sql/query/select.rst
Labels: english, manual

#188 [CBRD-23662] [10.2] translate english manual to korean - correct Korean manual
  ko/admin/admin_utils.rst
  ko/sql/catalog.rst
  ko/sql/schema/index_stmt.rst
  ko/upgrade.rst
Labels: korean, manual

#189 [CBRD-23662] [10.2] translate english manual to korean - modified version info
  en/conf.py
  ko/conf.py
Labels: manual

#190 [CBRD-23711] [Manual] Merge the release/10.2 branch to develop branch
  en/admin/admin_utils.rst
  en/conf.py
  en/env.rst
  en/sql/catalog.rst
  en/sql/query/select.rst
  ko/admin/admin_utils.rst
  ko/admin/config.rst
  ko/admin/control.rst
  ko/admin/db_manage.rst
  ko/conf.py
  ko/csql.rst
  ko/index.rst
  ko/install.rst
  ko/intro.rst
  ko/quick_start.rst
  ko/release_note/index.rst
  ko/release_note/release_note_latest_ver.rst
  ko/sql/catalog.rst
  ko/sql/schema/index_stmt.rst
  ko/sql/transaction.rst
  ko/toc.rst
  ko/upgrade.rst
Labels: manual
