Repository CUBRID/cubrid-manual, pull requests merged in 2020-12, with the labels that each got.

#203 [CUBRIDMAN-11] Adding a configuration parameter to allow truncated string.
  en/admin/config.rst
  en/sql/datatype.rst
  en/sql/schema/table_stmt.rst
Labels: english, manual

#214 [CUBRIDMAN-19] Fixed script in HA manual (Eng/Kor)
  en/ha.rst
  ko/ha.rst
Labels: english, korean, manual

#222 [CUBRIDMAN-19] Typo correction in odbc
  en/api/odbc.rst
  ko/api/odbc.rst
Labels: english, korean, manual

#228 [CUBRIDMAN-19] Added command in rebuilding scenario of HA (Eng/Kor)
  en/ha.rst
  ko/ha.rst
Labels: english, korean, manual

#227 [CUBRIDMAN-19] ;Get command result change in csql
  en/csql.rst
  ko/csql.rst
Labels: english, korean, manual

#217 [CUBRIDMAN-7] manual for CBRD-23649 (dual table)
  en/sql/catalog.rst
  en/sql/function/index.rst
  en/sql/tuning.rst
Labels: english, manual

#221 [CUBRIDMAN-4] [en, ko] create security.rst file for the newly added CUBRID Security section.
  en/index.rst
  en/security.rst
  en/toc.rst
  ko/index.rst
  ko/security.rst
  ko/toc.rst
Labels: english, korean, manual

#234 [CUBRIDMAN-35] Add "db_ha_apply_info" to result of example in DB_CLASS
  en/sql/catalog.rst
  ko/sql/catalog.rst
Labels: english, korean, manual

#232 [CUBRIDMAN-24] add query-output and loaddb-output option to csql utility
  en/csql.rst
  ko/csql.rst
Labels: english, korean

#210 [CUBRIDMAN-13] manual for Hash List Scan and Optional Statistics Estimation
  en/admin/config.rst
  en/sql/tuning.rst
Labels: english, manual

#233 [CUBRIDMAN-4] manual for CBRD-23608 (TDE)
  ko/admin/admin_utils.rst
  ko/admin/backup.inc
  ko/admin/config.rst
  ko/admin/migration.inc
  ko/ha.rst
  ko/images/tde_2_level_key.png
  ko/index.rst
  ko/intro.rst
  ko/security.rst
  ko/sql/catalog.rst
  ko/sql/schema/table_stmt.rst
Labels: korean, manual

#235 [CUBRIDMAN-20] change table option's default value to reuse_oid
  en/admin/config.rst
  en/sql/schema/table_stmt.rst
  ko/admin/config.rst
  ko/sql/schema/table_stmt.rst
Labels: english, korean

#241 [CUBRIDMAN-24] add query-output and loaddb-output option to csql utility
  en/csql.rst
  ko/csql.rst
Labels: english, korean

#226 [CUBRIDMAN-25] manual for change column comments without writing column definitions
  en/sql/schema/table_stmt.rst
  en/sql/schema/view_stmt.rst
  ko/sql/schema/table_stmt.rst
  ko/sql/schema/view_stmt.rst
Labels: english, korean, manual

#220 [CUBRIDMAN-7] manual for CBRD-23649 (dual table) (Korean)
  ko/sql/catalog.rst
  ko/sql/function/index.rst
  ko/sql/tuning.rst
Labels: korean, manual

#230 [CUBRIDMAN-19] Fixed result in BIT VARYING insertion
  en/sql/datatype.rst
  ko/sql/datatype.rst
Labels: english, korean, manual

#231 [CUBRIDMAN-19] Correction of typo
  en/api/jdbc.rst
  ko/api/jdbc.rst
Labels: english, korean, manual

#205 [CUBRIDMAN-14] Statement and result cache to improve performance for frequently repeated queries
  en/admin/config.rst
  en/sql/tuning.rst
Labels: english, manual

#206 [CUBRIDMAN-12] In data comparing, no ignoring to trailing spaces at the end of the data.
  en/sql/datatype.rst
Labels: english, manual, task

#229 [CUBRIDMAN-19] Fixed csql command in rebuilding scenario of HA (Eng/Kor)
  en/ha.rst
  ko/ha.rst
Labels: english, korean, manual

#242 [CUBRIDMAN-19] Typo correction in python.rst
  ko/api/python.rst
Labels: korean, manual

#243 [CUBRIDMAN-19] Fixed connection part of Python example program [Eng/Kor]
  en/api/python.rst
  ko/api/python.rst
Labels: english, korean, manual

#237 [CUBRIDMAN-19] Fix wrong date literal format [Eng/Kor]
  en/sql/literal.rst
  ko/sql/literal.rst
Labels: english, korean, manual

#246 [CUBRIDMAN-48] Sphinx documentation hosting server for dev environment
  en/dev.ini
  ko/dev.ini
Labels: enhancement

#192 [CUBRIDMAN-5] CUBRID Java Stored Procedure Server Utility
  en/admin/control.rst
  en/admin/index.rst
  en/api/jdbc.rst
  en/env.rst
  en/ha.rst
  en/intro.rst
  en/sql/jsp.rst
Labels: english, manual

#240 [CUBRIDMAN-5] CUBRID Java Stored Procedure Server Utility for Korean Manual
  ko/admin/control.rst
  ko/admin/index.rst
  ko/api/jdbc.rst
  ko/env.rst
  ko/ha.rst
  ko/intro.rst
  ko/sql/jsp.rst
Labels: korean, manual

#245 [CUBRIDMAN-47] New process structure figure
  en/images/process_structure.png
  en/images/process_structure.svg
  en/images/process_structure_old.png
  en/intro.rst
  ko/images/process_structure.png
  ko/images/process_structure.svg
  ko/images/process_structure_old.png
  ko/intro.rst
Labels: english, enhancement, korean, manual

#236 [CUBRIDMAN-16] Add description about JSON in Extending the Relational Data Model section
  en/intro.rst
  en/sql/datatype.rst
  en/sql/function/json_fn.rst
  ko/intro.rst
  ko/sql/datatype.rst
  ko/sql/function/json_fn.rst
Labels: english, korean, manual

#248 [CUBRIDMAN-19] Modify Python driver file name [Eng/Kor]
  en/api/python.rst
  ko/api/python.rst
Labels: english, korean, manual

#247 [CUBRIDMAN-46] manual for packet encryption
  ko/api/cciapi.rst
  ko/security.rst
Labels: korean, manual

#238 [CUBRIDMAN-26] Add of useSSL property description and usage example to CCI manual
  en/api/cciapi.rst
  ko/api/cciapi.rst
Labels: english, korean, manual

#251 [CUBRIDMAN-44] write ACL and authority of security section
  en/security.rst
  en/sql/authorization.rst
  ko/security.rst
  ko/sql/authorization.rst
Labels: english, korean

#253 [CUBRIDMAN-13] manual for Hash List Scan and Optional Statistics Estimation
  ko/admin/config.rst
  ko/sql/tuning.rst
Labels: korean, manual

#254 [CUBRIDMAN-9] [kr] The max length of CHAR-type changed to 256MB (specchanged)
  ko/sql/datatype.rst
Labels: korean, manual

#252 [CUBRIDMAN-3] manual for CBRD-22803 (show statement for page buffer status)
  en/sql/query/show.rst
  ko/sql/query/show.rst
Labels: english, korean, manual

#250 [CUBRIDMAN-4] Fix some missing in Korean manual for CBRD-23608 (TDE)
  ko/admin/admin_utils.rst
  ko/admin/backup.inc
  ko/security.rst
  ko/sql/oodb.rst
  ko/sql/schema/table_stmt.rst
Labels: bug, korean, manual

#256 [CUBRIDMAN-12] [kr] In data comparing, no ignoring to trailing spaces at the end of the data.
  ko/sql/datatype.rst
Labels: korean, manual

#255 [CUBRIDMAN-11] [kr] Adding a configuration parameter to allow truncated string.
  ko/admin/config.rst
  ko/sql/datatype.rst
  ko/sql/schema/table_stmt.rst
Labels: korean, manual

#257 [CUBRIDMAN-34] Add a description of the spec that cubrid server and javasp refer to service::server if db_name is omitted
  en/admin/control.rst
  ko/admin/control.rst
Labels: english, korean, manual

#249 [CUBRIDMAN-4] english manual for CBRD-23608 (TDE)
  en/admin/admin_utils.rst
  en/admin/backup.inc
  en/admin/config.rst
  en/admin/migration.inc
  en/ha.rst
  en/images/tde_2_level_key.png
  en/index.rst
  en/intro.rst
  en/security.rst
  en/sql/catalog.rst
  en/sql/oodb.rst
  en/sql/schema/table_stmt.rst
Labels: english, manual

#258 [CUBRIDMAN-14] [kr] Statement and result cache to improve performance for frequently repeated queries
  en/admin/config.rst
  en/sql/tuning.rst
  ko/admin/config.rst
  ko/sql/tuning.rst
Labels: english, korean, manual

#259 [CUBRIDMAN-46] manual for packet encryption.(english)
  en/security.rst
Labels: english, manual

#260 [CUBRIDMAN-27] manual for DDL Audit (English/Korean)
  en/admin/config.rst
  en/admin/ddl_audit.rst
  en/admin/index.rst
  ko/admin/config.rst
  ko/admin/ddl_audit.rst
  ko/admin/index.rst
Labels: english, korean, manual

#261 [CUBRIDMAN-29] manual for CBRD-23678
  en/ha.rst
  en/sql/tuning.rst
  ko/ha.rst
  ko/sql/tuning.rst
Labels: english, korean, manual

#262 [CUBRIDMAN-19] fix malformed table and warning error
  en/admin/config.rst
  en/admin/control.rst
  en/ha.rst
  ko/admin/control.rst
  ko/admin/migration.inc
  ko/conf.py
  ko/ha.rst
  ko/sql/datatype.rst
Labels: bug, english, korean

#263 [CUBRIDMAN-24] add query-output and loaddb-output option to csql utility
  en/csql.rst
  ko/csql.rst
Labels: english, korean

#239 [CUBRIDMAN-43] Update upgrade section
  en/sql/jsp.rst
  en/upgrade.rst
  ko/sql/jsp.rst
  ko/upgrade.rst
Labels: english, korean, manual

#264 [CUBRIDMAN-30] manual for CBRD-23682
  en/sql/tuning.rst
  ko/sql/tuning.rst
Labels: english, korean, manual
