Repository CUBRID/cubrid-manual, pull requests merged in 2020-06, with the labels that each got.

#118 [CBRD-23657] change broken/redirect url in manual
  en/api/adodotnet.rst
  en/api/jdbc.rst
  en/api/node_js.rst
  en/api/odbc.rst
  en/api/oledb.rst
  en/api/pdo.rst
  en/api/perl.rst
  en/api/php.rst
  en/api/python.rst
  en/ha.rst
  en/install.rst
  en/install_upgrade.rst
  en/qrytool.rst
  en/release_note/index.rst
  en/release_note/release_note_latest_ver.rst
  en/sql/datatype.rst
  en/sql/i18n.rst
  en/sql/jsp.rst
  en/start.rst
  en/upgrade.rst
  ko/api/adodotnet.rst
  ko/api/php.rst
  ko/api/python.rst
  ko/release_note/release_note_latest_ver.rst
Labels: english, manual

#117 [CBRD-23657] Fix broken and permanently redirected links
  en/api/adodotnet.rst
  en/api/jdbc.rst
  en/api/node_js.rst
  en/api/odbc.rst
  en/api/oledb.rst
  en/api/pdo.rst
  en/api/perl.rst
  en/api/php.rst
  en/api/python.rst
  en/ha.rst
  en/install.rst
  en/install_upgrade.rst
  en/qrytool.rst
  en/release_note/index.rst
  en/release_note/release_note_latest_ver.rst
  en/sql/datatype.rst
  en/sql/i18n.rst
  en/sql/jsp.rst
  en/start.rst
  en/upgrade.rst
  ko/api/adodotnet.rst
  ko/api/php.rst
  ko/api/python.rst
  ko/release_note/release_note_latest_ver.rst
Labels: manual

#125 [CBRD-23654] Fix wrong broken link error
  en/conf.py
  ko/conf.py
Labels: bug, task

#126 [CBRD-23676] Fix warnings in english manual
  en/conf.py
  en/sql/datatype.rst
  en/upgrade.rst
Labels: english, task

#111 [CBRD-23662] Translate JSON in data type section
  ko/sql/datatype.rst
  ko/sql/function/typecast_fn.rst
Labels: korean, manual

#121 [CBRD-23676] Fix malformed table warning
  en/sql/function/regex_fn.rst
Labels: manual

#127 [CBRD-23662] Translate JSON in data type section (#111)
  ko/sql/datatype.rst
  ko/sql/function/typecast_fn.rst
Labels: korean, manual

#128 [CBRD-23662] Translate JSON aggregate functions (#112)
  ko/sql/function/analysis_fn.rst
Labels: korean, manual

#129 [CBRD-23662] Translate update compatibility chapter (#114)
  ko/install.rst
Labels: korean, manual

#130 [CBRD-23662] Translate JSON system parameter (#113)
  ko/admin/config.rst
Labels: korean, manual

#131 [CBRD-23676] Fix warnings in english manual (#126)
  en/conf.py
  en/sql/datatype.rst
  en/upgrade.rst
Labels: task

#132 [CBRD-23654] Fix wrong broken link error (#125)
  en/conf.py
  ko/conf.py
Labels: task

#116 [CBRD-23662] json-function: translate english manual to korean
  ko/sql/function/json_fn.rst
Labels: korean, manual

#123 [CBRD-23657] change broken/redirect url in manual(korea)
  ko/api/adodotnet.rst
  ko/api/jdbc.rst
  ko/api/node_js.rst
  ko/api/odbc.rst
  ko/api/oledb.rst
  ko/api/pdo.rst
  ko/api/perl.rst
  ko/api/php.rst
  ko/api/python.rst
  ko/ha.rst
  ko/install.rst
  ko/install_upgrade.rst
  ko/qrytool.rst
  ko/release_note/index.rst
  ko/release_note/release_note_latest_ver.rst
  ko/sql/i18n.rst
  ko/sql/jsp.rst
  ko/start.rst
  ko/upgrade.rst
Labels: korean, manual

#124 [CBRD-23657] change broken/redirect url in manual(korea)
  ko/api/adodotnet.rst
  ko/api/jdbc.rst
  ko/api/node_js.rst
  ko/api/odbc.rst
  ko/api/oledb.rst
  ko/api/pdo.rst
  ko/api/perl.rst
  ko/api/php.rst
  ko/api/python.rst
  ko/ha.rst
  ko/install.rst
  ko/install_upgrade.rst
  ko/qrytool.rst
  ko/release_note/index.rst
  ko/release_note/release_note_latest_ver.rst
  ko/sql/i18n.rst
  ko/sql/jsp.rst
  ko/start.rst
  ko/upgrade.rst
Labels: korean, manual

#134 [CBRD-23654] Change ignoring pattern for korean manual
  ko/conf.py
Labels: korean, manual

#135 [CBRD-23654] Change ignoring URL pattern for korean manual (#134)
  ko/conf.py
Labels: task

#119 [CBRD-23674] modification of English manual by changing the maximum value of the ha_apply_max_mem_size property.
  en/ha.rst
  en/upgrade.rst
Labels: english, manual

#133 [CBRD-23674] modification of Korean manual by changing the maximum value of the ha_apply_max_mem_size property.
  ko/ha.rst
  ko/upgrade.rst
Labels: korean, manual

#136 [CBRD-23674] modification of English manual by changing the maximum value of the ha_apply_max_mem_size property. (#119)
  en/ha.rst
  en/upgrade.rst
Labels: english, manual

#137 [CBRD-23674] modification of Korean manual by changing the maximum value of the ha_apply_max_mem_size property. (#133)
  ko/ha.rst
  ko/upgrade.rst
Labels: korean, manual

#120 [CBRD-23639] Broker/CAS SSL support
  en/admin/config.rst
  en/admin/control.rst
  ko/admin/config.rst
  ko/admin/control.rst
Labels: manual

#138 [CBRD-23662] translate english to korean - activation flags
  ko/admin/admin_utils.rst
Labels: manual

#140 [CBRD-23662] translate english to korean - Fix warnings
  ko/admin/config.rst
Labels: manual

#139 [CBRD-23662] translate english to korean - Add CTE for DML & CREATE e…
  ko/sql/query/cte.rst
Labels: manual

#142 [CBRD-23662] translate english to korean - 10.2 Release Notes
  ko/release_note/changes_10_1.rst
  ko/release_note/index.rst
  ko/release_note/release_note_latest_ver.rst
Labels: manual

#141 [CBRD-23662] translate english to korean - upgrade to 10.2
  ko/admin/control.rst
  ko/csql.rst
  ko/index.rst
  ko/install.rst
  ko/quick_start.rst
  ko/toc.rst
  ko/upgrade.rst
Labels: manual

#143 Revert "[CBRD-23674] modification of English manual by changing the maximum value of the ha_apply_max_mem_size property. (#119)"
  en/ha.rst
  en/upgrade.rst
Labels: english, manual, wontfix

#144 Revert "[CBRD-23674] modification of Korean manual by changing the maximum value of the ha_apply_max_mem_size property. (#133)"
  ko/ha.rst
  ko/upgrade.rst
Labels: korean, manual, wontfix

#145 [CBRD-23662] Translate Invisible index manual (#87)
  ko/sql/catalog.rst
  ko/sql/query/show.rst
  ko/sql/schema/index_stmt.rst
Labels: korean, manual

#147 [CBRD-23662] Translate loaddb manual into Korean (#74)
  ko/admin/migration.inc
Labels: korean, manual

#150 [CBRD-23662] Translate backupdb into Korean (#81)
  ko/admin/backup.inc
Labels: korean, manual

#151 [CBRD-23662] Translate ON UPDATE into Korean (#80)
  ko/sql/schema/table_stmt.rst
Labels: korean, manual

#152 [CBRD-23662] Translate online index (#60) into Korean
  ko/sql/catalog.rst
  ko/sql/schema/index_stmt.rst
Labels: korean, manual

#157 [CBRD-23662] Fix markup error of Korean manual - json function section (#91)
  ko/sql/function/json_fn.rst
Labels: korean, manual

#153 [CBRD-23662] Translate ON UPDATE (#80) into Korea
  ko/sql/schema/table_stmt.rst
Labels: korean, manual

#161 [CBRD-23662] Fix ON UPDATE (#80) Reference
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: korean, manual

#159 [CBRD-23662] Translate CTE (#91) and make it consitent with English m…
  ko/sql/query/cte.rst
Labels: korean, manual

#164 [CBRD-23662] On UPDATE backport to 10.2
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: backport, korean, manual

#163 [CBRD-23662] Translate Invisible index manual (#87) (#145)
  ko/sql/catalog.rst
  ko/sql/query/show.rst
  ko/sql/schema/index_stmt.rst
Labels: backport, korean, manual

#167 [CBRD-23662] [backport] Translate backupdb into Korean (#81) (#150)
  ko/admin/backup.inc
Labels: backport, korean, manual

#166 [CBRD-23662] [backport] Translate loaddb manual into Korean (#74) (#147)
  ko/admin/migration.inc
Labels: backport, korean, manual

#165 [CBRD-23662] [backport] Translate online index (#60) into Korean (#152)
  ko/sql/catalog.rst
  ko/sql/schema/index_stmt.rst
Labels: backport, korean, manual

#162 [CBRD-23662] json-function: translate english manual to korean
  ko/sql/function/index.rst
  ko/sql/function/json_fn.rst
Labels: backport, korean, manual, task

#169 [CBRD-23662] CTE Translation: leave command output in English
  ko/sql/query/cte.rst
Labels: korean, manual

#154 [CBRD-23662] translate english manual to korean - [CBRD-23493] thread related parameters (#76)
  ko/admin/config.rst
Labels: korean, manual

#160 [CBRD-23662] translate english manual to korean - [CBRD-23493] data_file_os_advise system parameter (#75)
  ko/admin/config.rst
Labels: korean, manual

#168 [CBRD-23662] [backport] CTE(#91) translate into Korean
  ko/sql/query/cte.rst
Labels: backport, korean, manual

#155 [CBRD-23662] translate english manual to korean (PHP Driver)
  ko/api/php.rst
  ko/images/image57.jpg
  ko/images/image58.jpg
Labels: korean, manual

#170 [CBRD-23662] translate english manual to korean - [CBRD-23494] thread statistics (#71)
  ko/admin/admin_utils.rst
Labels: korean, manual

#171 [CBRD-23662] translate english manual to korean - [CBRD-23494] load index online stats (#67)
  ko/admin/admin_utils.rst
Labels: korean, manual

#172 Update broker_log_top usage in Korean
  ko/admin/control.rst
Labels: korean, manual

#176 Update broker_log_top usage in Korean
  ko/admin/control.rst
Labels: korean, manual

#180 Update broker_log_top usage
  en/admin/control.rst
Labels: english, manual

#181 [CBRD-23662] translate english manual to korean - [CBRD-23494] Split all statistics table (#64)
  ko/admin/admin_utils.rst
Labels: korean, manual
