Repository CUBRID/cubrid-manual, pull requests merged in 2021-03, with the labels that each got.

#274 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail. (english/korea)
  en/install.rst
  ko/install.rst
Labels: bug

#276 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail. (english/korea)
  en/install.rst
  ko/install.rst
Labels: bug, english, korean

#275 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail. (english/korea)
  en/install.rst
  ko/install.rst
Labels: bug

#273 [CUBRIDMAN-51] Fix typos, incorrect description, examples and results.
  en/ha.rst
  ko/ha.rst
Labels: english, korean, manual
