Repository CUBRID/cubrid-manual, pull requests merged in 2021-01, with the labels that each got.

#265 [CUBRIDMAN-32] change CUBRID version
  en/admin/control.rst
  en/api/jdbc.rst
  en/api/python.rst
  en/conf.py
  en/csql.rst
  en/index.rst
  en/install.rst
  en/quick_start.rst
  en/release_note/index.rst
  en/release_note/release_note_latest_ver.rst
  ko/admin/control.rst
  ko/api/jdbc.rst
  ko/api/python.rst
  ko/conf.py
  ko/csql.rst
  ko/index.rst
  ko/install.rst
  ko/quick_start.rst
  ko/release_note/index.rst
  ko/release_note/release_note_latest_ver.rst
Labels: english, korean

#266 [CUBRIDMAN-49] change license
  en/release_note/index.rst
  ko/release_note/index.rst
Labels: english, korean

#267 [CUBRIDMAN-32] change CUBRID version
  en/admin/control.rst
  en/api/jdbc.rst
  en/install.rst
  en/release_note/index.rst
  ko/admin/control.rst
  ko/api/jdbc.rst
  ko/install.rst
  ko/release_note/index.rst
Labels: english, korean

#269 [CUBRIDMAN-50] Result-cache related property parameter for JDBC
  en/admin/config.rst
  en/api/jdbc.rst
  ko/admin/config.rst
  ko/api/jdbc.rst
Labels: english, korean, manual, task

#271 [CUBRIDMAN-50] [revised] Result-cache related property parameter for JDBC
  en/admin/config.rst
  ko/admin/config.rst
Labels: english, korean, manual, task

#272 [CUBRIDMAN-50] [re-revised] Result-cache related property parameter for JDBC
  ko/api/jdbc.rst
Labels: korean, manual, task
