Repository CUBRID/cubrid-manual, pull requests merged in 2023-09, with the labels that each got.

#457 [CUBRIDMAN-173] The use of synonyms is not allowed in the update statistics statement (#421)
  en/sql/tuning.rst
  ko/admin/migration.inc
  ko/sql/tuning.rst
Labels: backport

#458 [CUBRIDMAN-144] manual for not updating statistics when performing DDL (#379)
  en/sql/tuning.rst
  ko/sql/tuning.rst
Labels: backport

#459 [CUBRIDMAN-144] manual for not updating statistics when performing DDL (#379)
  en/sql/tuning.rst
  ko/sql/tuning.rst
Labels: backport

#460 [CUBRIDMAN-144] manual for not updating statistics when performing DDL (#379)
  en/sql/tuning.rst
  ko/sql/tuning.rst
Labels: backport

#461 [CUBRIDMAN-178] not allow to alter the column type to a type that does not support auto-increment.
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: backport

#465 [CUBRIDMAN-196] Modify description of mod function
  en/sql/function/numeric_fn.rst
  ko/sql/function/numeric_fn.rst
Labels: bug

#466 [CUBRIDMAN-197] modify the description about notes and constraints for dblink
  en/sql/dblink.rst
  ko/sql/dblink.rst
Labels: enhancement
