Repository CUBRID/cubrid-manual, pull requests merged in 2023-08, with the labels that each got.

#435 [CUBRIDMAN-110] Change the 'Result of NUMERIC Type Operation' simply (#416)
  en/sql/function/arithmetic_op.rst
  ko/api/node_js.rst
  ko/sql/function/arithmetic_op.rst
Labels: backport

#436 [CUBRIDMAN-174] reflect reuse-oid option in error message prining at view updating query.
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: enhancement

#443 [CUBRIDMAN-179] The problem of the default value of column when altering the type of column.
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: bug

#440 [CUBRIDMAN-177] replace the information which is printed in "show trace" from aggregate function optimization
  en/sql/tuning.rst
  ko/sql/tuning.rst
Labels: enhancement

#442 [CUBRIDMAN-178] not allow to alter the column type to a type that does not support auto-increment.
  en/sql/schema/table_stmt.rst
  ko/sql/schema/table_stmt.rst
Labels: enhancement, task

#439 [CUBRIDMAN-175] A new system parameter oracle_compat_number_behavior
  en/admin/config.rst
  ko/admin/config.rst
Labels: task

#438 [CUBRIDMAN-176] divide operation result into NUMERIC type
  en/sql/function/arithmetic_op.rst
  ko/sql/function/arithmetic_op.rst
Labels: task

#444 [CUBRIDMAN-153] extending dblink syntax and adding dblink DML related
  en/sql/dblink.rst
  en/sql/query/delete.rst
  en/sql/query/insert.rst
  en/sql/query/merge.rst
  en/sql/query/replace.rst
  en/sql/query/select.rst
  en/sql/query/update.rst
  en/sql/schema/table_stmt.rst
  ko/sql/dblink.rst
  ko/sql/query/delete.rst
  ko/sql/query/insert.rst
  ko/sql/query/merge.rst
  ko/sql/query/replace.rst
  ko/sql/query/select.rst
  ko/sql/query/update.rst
  ko/sql/schema/table_stmt.rst
Labels: task
